CREATE DATABASE IF NOT EXISTS memigo_v2;
USE memigo_v2;

CREATE TABLE users (
    userId VARCHAR(16) NOT NULL UNIQUE,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    userpfp MEDIUMTEXT NULL,
    creationDate DATETIME NOT NULL,
    PRIMARY KEY(userId)
);

CREATE TABLE templates(
    templateId INT NOT NULL AUTO_INCREMENT,
    template MEDIUMTEXT NOT NULL,
    PRIMARY KEY(templateId)  
);

CREATE TABLE memes(
    memeId INT NOT NULL AUTO_INCREMENT,
    userId VARCHAR(16) NOT NULL,
    meme MEDIUMTEXT NOT NULL,
    postDesc VARCHAR(255) NULL,
    likes INT NOT NULL DEFAULT 0,
    postDate DATETIME NOT NULL,
    PRIMARY KEY(memeId),
    FOREIGN KEY (userId) REFERENCES users(userId) ON DELETE CASCADE
);
